# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79e3b1ea36b6147316a408657e9aea455abce16eaf41c685c800e915e913ee8d3ae7ab1ee4fcf590df13bd2eefdf3feefd59495437f2a1e12a8ea40e2cac565a

test:
  secret_key_base: f3c2068d4fb752f483adea8ba0c1835209d33e82e34fd0ac113161bf95643f2f122dd87127149edd7879667beb41a46795df5c0da183e2b8a1b3ac1382fa6a4b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
